#!/bin/bash

cat /etc/passwd | grep '/home/' | \
grep -v 'cups\|syslog' | cut -d ':' -f 6 > /tmp/homes.list

while read BASEDIR; do
    rm -rf "$BASEDIR/Desktop/arduino-ide.desktop"
    rm -rf "$BASEDIR/.arduino15/"
done < /tmp/homes.list