#!/bin/bash

cat /etc/passwd | grep '/home/' | \
grep -v 'cups\|syslog' | cut -d ':' -f 1 > /tmp/homes.list

while read USUARIO; do
 	runuser -l $USUARIO -c "mkdir -p /home/$USUARIO/.arduino15/"
	runuser -l $USUARIO -c \
	"cp -rf /tmp/arduino/preferences.txt /home/$USUARIO/.arduino15/"

	cp /usr/share/applications/arduino-bionic.desktop /home/$USUARIO/Desktop/arduino-bionic.desktop

	runuser -l $USUARIO -c "rm -rf /home/$USUARIO/.cache/"
	if [ -f /usr/bin/lxpanelctl ]; then
		su - $USUARIO -c "lxpanelctl restart"
	fi
done < /tmp/homes.list
